# vim:set ft=tmux:
%hidden MODULE_NAME="brew"

set -ogq "@catppuccin_${MODULE_NAME}_icon" "󰏔 "
set -ogqF "@catppuccin_${MODULE_NAME}_color" "#{E:@thm_peach}"
set -ogq "@catppuccin_${MODULE_NAME}_text" " #(~/.tmux/plugins/brew-tmux/brew.tmux)"

source -F "~/.tmux/plugins/tmux/utils/status_module.conf"

